name: PR build

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: |
          mkdir -p _site
          ./go.sh build

      - uses: anishathalye/proof-html@v2
        with:
          directory: ./_site
          enforce_https: false
          ignore_empty_alt: true
          ignore_url: |
            https://www.baeldung.com
