name: PR build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: |
          mkdir -p _site
          ./go.sh build
